[package]
name = "proto"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
packet = {path="../packet"}
serde = {version = "1", features = ["derive"]}
bincode = {version = "1.3.3"}
tracing="*"